In [1]:
import numpy as np

In [2]:
"""
numpy array attributes
"""
#creating an array
print(np.arange(3))
print(np.arange(3,9))
print(np.arange(3,9,3))

[0 1 2]
[3 4 5 6 7 8]
[3 6]


In [3]:
# random number
np.random.seed(0) #이게 있으면 똑같은 난수 배열 생성을 한다.

arr1= np.random.randint(10, size=6)
arr2= np.random.randint(10, size=(3,4))
arr3= np.random.randint(10, size=(3,4,5))
print(arr1)
print(arr2)
print(arr3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [4]:
#attribute
print(arr2)

print("arr.ndim = ", arr2.ndim)
print("arr.shape = ", arr2.shape)
print("arr.size = ", arr2.size)
print("arr.dtype = ", arr2.dtype)
print("arr.itemsize = ", arr2.itemsize)
print("arr.nbytes = ", arr2.nbytes)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
arr.ndim =  2
arr.shape =  (3, 4)
arr.size =  12
arr.dtype =  int32
arr.itemsize =  4
arr.nbytes =  48


In [5]:
"""
array slicing
"""
arr = np.arange(10)
print(arr)

print(arr[3:7])
print(arr[:5])
print(arr[5:])
print(arr[::3])
print(arr[2:8:2])

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6]
[0 1 2 3 4]
[5 6 7 8 9]
[0 3 6 9]
[2 4 6]


In [6]:
#multi-dimensional 
np.random.seed(0)
arr = np.random.randint(10, size=(6,8))
print(arr)
arr_sub = arr[3:5, 4:6]
print(arr_sub)

[[5 0 3 3 7 9 3 5]
 [2 4 7 6 8 8 1 6]
 [7 7 8 1 5 9 8 9]
 [4 3 0 3 5 0 2 3]
 [8 1 3 3 3 7 0 1]
 [9 9 0 4 7 3 2 7]]
[[5 0]
 [3 7]]


In [7]:
#subarrays as no-copy views
np.random.seed(0)
arr = np.random.randint(10, size=(3,4))
print(arr,"\n")
arr_sub = arr[:2,:2]
print(arr_sub,"\n")

#배열 슬라이스 값을 변경
arr_sub[0,0] = 99
print(arr_sub,"\n")

#원본배열 값도 변경됨
print(arr,"\n")

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]] 

[[5 0]
 [7 9]] 

[[99  0]
 [ 7  9]] 

[[99  0  3  3]
 [ 7  9  3  5]
 [ 2  4  7  6]] 



In [8]:
#.copy() -> 복사본 생성 
np.random.seed(0)
arr = np.random.randint(10, size=(3,4))
print(arr,"\n")

arr_sub = arr[:2, :2].copy()
print(arr_sub,"\n")
arr_sub[0,0] = 99
print(arr_sub,"\n")

#복사본의 배열 값을 변경했기 때문에, 원본 베열 값은 변하지 않는다. 
print(arr,"\n")

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]] 

[[5 0]
 [7 9]] 

[[99  0]
 [ 7  9]] 

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]] 



In [9]:
#np.newaxis
arr = np.array([1,2,3])
print(arr)
print("arr.ndim = ", arr.ndim)
print("arr.shape = ", arr.shape)

arr_new = arr[np.newaxis, :]
print(arr_new)
print("arr_new.ndim = ", arr_new.ndim)
print("arr_new.shape = ", arr_new.shape)

arr_new2 = arr[:,np.newaxis]
print(arr_new2)
print("arr_new2.ndim = ", arr_new2.ndim)
print("arr_new2.shape = ", arr_new2.shape)

[1 2 3]
arr.ndim =  1
arr.shape =  (3,)
[[1 2 3]]
arr_new.ndim =  2
arr_new.shape =  (1, 3)
[[1]
 [2]
 [3]]
arr_new2.ndim =  2
arr_new2.shape =  (3, 1)


In [10]:
"""
array concatenation
"""
arr_1 = ([1,2,3])
arr_2 = ([4,5,6])
arr_3 = ([7,8,9])

arr_total = np.concatenate([arr_1, arr_2,arr_3])
print (arr_total,'\n')

[1 2 3 4 5 6 7 8 9] 



In [11]:
"""
array splitting
"""
arr = [1,2,3,99,99,3,2,1]
print(arr,'\n')

arr_1, arr_2, arr_3 =np.split(arr, [3,5])
print(arr_1, arr_2, arr_3)

[1, 2, 3, 99, 99, 3, 2, 1] 

[1 2 3] [99 99] [3 2 1]
