In [1]:
import numpy as np

In [2]:
"""
computing reciporocals in loops
"""
#functions for computing reciporcals using looping 
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/ values[i]
    return output

values = np.random.randint(1,10, size = 5)
print(values)

[3 6 8 4 2]


In [3]:
"""
comparison : loop vs ufuncs (vectorized)
"""

big_array = np.random.randint(1, 100, size = 1000000)
#looping on a big array

#jupyter magic function 
%timeit compute_reciprocals(big_array)

1.84 s ± 46.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
%timeit 1/ big_array

3.78 ms ± 248 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
np.random.seed(0)
arr1 = np.random.randint(10, size = 5)
arr2 = np.random.randint(10, size = 5)
arr3 = np.random.randint(10, size = 5)
arr4 = np.random.randint(10, size = 5)
arr5 = np.random.randint(10, size = 5)


arr1 = arr1 - 2
print(arr1, arr2)
arr3 = arr1 + arr2
print(arr3)
arr4 = np.random.randint(10, size=(3,5))
print(arr4)
arr5 = arr4 **2
print(arr5)

[ 3 -2  1  1  5] [9 3 5 2 4]
[12  1  6  3  9]
[[3 0 3 5 0]
 [2 3 8 1 3]
 [3 3 7 0 1]]
[[ 9  0  9 25  0]
 [ 4  9 64  1  9]
 [ 9  9 49  0  1]]


In [6]:
"""
ufuns : absolute value
"""
x = np.array([-2,-1,0,1,2])
print(np.abs(x))

y = np.array([3-4j, 4-3j,2+0j, 0+1j])
print(np.abs(y))

[2 1 0 1 2]
[5. 5. 2. 1.]


In [7]:
#linspace
x = np.linspace(0, 100, 5)
print(x)

[  0.  25.  50.  75. 100.]


In [8]:
"""
trigonometic functions
"""
theta = np.linspace(0, np.pi, 3)
print (theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [9]:
"""
ufuncs : aggregation
"""
# reduce()
x = np.arange(1,5)
aggr = np.add.reduce(x)
print(aggr)
aggr = np.multiply.reduce(x)
print(aggr)

10
24


In [10]:
#accumulate()
print (x)
accum = np.add.accumulate(x)
print(accum)
accum = np.multiply.accumulate(x)
print(accum)

[1 2 3 4]
[ 1  3  6 10]
[ 1  2  6 24]


In [11]:
#np.sum()
np.random.seed(0)
arr = np.random.rand(1000000)  # rand(): creat 0~1 real numbers
np.sum(arr)

%timeit sum(arr)

78.2 ms ± 3.86 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [12]:
%timeit np.sum(arr)  # np.sum()이 파이썬 내장함수 sum()보다 훨씬 빠름

1.5 ms ± 101 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [13]:
#other aggregation function 

print("max = ", np.max(arr))
print("min = ", np.min(arr))
print("mean = ", np.mean(arr))
print("median = ", np.median(arr))
print("percentile = ", np.percentile(arr, 50))

print(np.any(arr>1))
print(np.all(arr>0))

max =  0.9999997207656334
min =  7.071203171893359e-07
mean =  0.5003876981207729
median =  0.5008080231177152
percentile =  0.5008080231177152
False
True


In [14]:
#multi dimensional aggregates

np.random.seed(0)
arr = np.random.randint(100, size=(3,4))
print(arr)
print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))

[[44 47 64 67]
 [67  9 83 21]
 [36 87 70 88]]
[147 143 217 176]
[222 180 281]
